pub const TWITTER_CONSUMER_TOKEN: &str = env!("TWITTER_CONSUMER_TOKEN");
pub const TWITTER_CONSUMER_SECRET: &str = env!("TWITTER_CONSUMER_SECRET");
pub const TWITTER_CALLBACK_URL: &str = env!("TWITTER_CALLBACK_URL");
